// Copy of restaurant data as a module for Next.js
// This is imported by all page components

export const restaurants = [
  { id: "la-barbecue", name: "La Barbecue", address: "2401 E Cesar Chavez St", cuisine: "BBQ", price: 18, walkMinutes: 15, vibe: "casual", tags: ["smoky","outdoor","meat-lovers","hearty"], popularDishes: ["Brisket","Pulled Pork Sandwich","Beef Ribs"], vegetarianFriendly: false, lunchHours: "11:00 AM - 6:00 PM", rating: 4.7, googleMapsUrl: "https://maps.google.com/?q=La+Barbecue+Austin+TX", description: "Legendary East Austin BBQ with lines worth the wait." },
  { id: "via-313", name: "Via 313", address: "1802 E 6th St", cuisine: "Pizza", price: 16, walkMinutes: 10, vibe: "casual", tags: ["cheesy","detroit-style","comfort","shareable"], popularDishes: ["The Detroiter","Cadillac","The Marinara"], vegetarianFriendly: true, lunchHours: "11:00 AM - 11:00 PM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Via+313+East+6th+Austin+TX", description: "Detroit-style deep dish pizza with crispy cheese edges." },
  { id: "nixta-taqueria", name: "Nixta Taqueria", address: "2512 E 12th St", cuisine: "Mexican", price: 14, walkMinutes: 18, vibe: "casual", tags: ["heirloom-corn","creative","unique","quick"], popularDishes: ["Duck Carnitas Taco","Migas Taco","Masa Fries"], vegetarianFriendly: true, lunchHours: "8:00 AM - 2:00 PM", rating: 4.8, googleMapsUrl: "https://maps.google.com/?q=Nixta+Taqueria+Austin+TX", description: "Heirloom corn tacos that redefine the taco game." },
  { id: "ramen-tatsuya", name: "Ramen Tatsu-ya", address: "1600 E 6th St", cuisine: "Japanese", price: 17, walkMinutes: 8, vibe: "casual", tags: ["ramen","umami","cozy","warm"], popularDishes: ["Original Tonkotsu","Vegan Ramen","Underbelly"], vegetarianFriendly: true, lunchHours: "11:00 AM - 10:00 PM", rating: 4.7, googleMapsUrl: "https://maps.google.com/?q=Ramen+Tatsu-ya+E+6th+Austin+TX", description: "Austin's best ramen, no debate." },
  { id: "discada", name: "Discada", address: "1700 E Cesar Chavez St", cuisine: "Mexican", price: 8, walkMinutes: 10, vibe: "food-truck", tags: ["street-food","quick","authentic","cheap"], popularDishes: ["Discada Taco","Al Pastor","Quesadilla"], vegetarianFriendly: false, lunchHours: "7:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Discada+Austin+TX", description: "Mexico City street tacos from a legendary truck." },
  { id: "joes-bakery", name: "Joe's Bakery", address: "2305 E 7th St", cuisine: "Tex-Mex", price: 10, walkMinutes: 12, vibe: "casual", tags: ["breakfast","comfort","classic","cheap"], popularDishes: ["Migas Plate","Carne Guisada","Puffy Tacos"], vegetarianFriendly: true, lunchHours: "6:00 AM - 3:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Joe's+Bakery+Austin+TX", description: "Old-school Tex-Mex breakfast & lunch institution." },
  { id: "juan-in-a-million", name: "Juan in a Million", address: "2300 E Cesar Chavez St", cuisine: "Tex-Mex", price: 9, walkMinutes: 14, vibe: "casual", tags: ["breakfast","tacos","classic","cheap","hearty"], popularDishes: ["Don Juan Taco","Carne Guisada","Barbacoa"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Juan+in+a+Million+Austin+TX", description: "Home of the famous Don Juan breakfast taco." },
  { id: "el-pollo-rey", name: "El Pollo Rey", address: "2209 E Cesar Chavez St", cuisine: "Mexican", price: 11, walkMinutes: 14, vibe: "casual", tags: ["grilled-chicken","quick","authentic","cheap"], popularDishes: ["Whole Grilled Chicken","Chicken Plate","Tacos"], vegetarianFriendly: false, lunchHours: "10:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=El+Pollo+Rey+Austin+TX", description: "Perfectly grilled chicken, no frills." },
  { id: "buenos-aires-cafe", name: "Buenos Aires Cafe", address: "1201 E 6th St", cuisine: "Argentine", price: 18, walkMinutes: 5, vibe: "casual", tags: ["empanadas","steak","south-american","cozy"], popularDishes: ["Empanadas","Milanesa","Grilled Steak"], vegetarianFriendly: true, lunchHours: "11:00 AM - 10:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Buenos+Aires+Cafe+Austin+TX", description: "Authentic Argentine food, closest to the office." },
  { id: "tamale-house-east", name: "Tamale House East", address: "1707 E 6th St", cuisine: "Tex-Mex", price: 9, walkMinutes: 9, vibe: "casual", tags: ["tamales","breakfast","classic","cheap","quick"], popularDishes: ["Tamales","Migas Taco","Carne Guisada Plate"], vegetarianFriendly: true, lunchHours: "7:00 AM - 2:30 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Tamale+House+East+Austin+TX", description: "East Austin tamale institution since forever." },
  { id: "revelry", name: "Revelry Kitchen + Bar", address: "1410 E 6th St", cuisine: "American", price: 15, walkMinutes: 7, vibe: "casual", tags: ["burgers","bar-food","outdoor","chill"], popularDishes: ["Smash Burger","Chicken Sandwich","Fries"], vegetarianFriendly: true, lunchHours: "11:00 AM - 12:00 AM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Revelry+Kitchen+Bar+Austin+TX", description: "Solid burgers and chill patio vibes." },
  { id: "oko", name: "OKO", address: "1308 E 6th St", cuisine: "Filipino", price: 14, walkMinutes: 6, vibe: "casual", tags: ["street-food","unique","bold-flavors","quick"], popularDishes: ["Sisig","Lumpia","Adobo Bowl"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=OKO+Filipino+Austin+TX", description: "Filipino street food with big bold flavors." },
  { id: "li-neighborhood", name: "Li Neighborhood Noodles", address: "1900 E 6th St", cuisine: "Chinese", price: 12, walkMinutes: 11, vibe: "casual", tags: ["noodles","hand-pulled","authentic","cheap","warm"], popularDishes: ["Biang Biang Noodles","Lamb Burger","Cold Noodles"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Li+Neighborhood+Noodles+Austin+TX", description: "Hand-pulled noodles and authentic Xi'an flavors." },
  { id: "cenote", name: "Cenote", address: "1010 E Cesar Chavez St", cuisine: "Cafe", price: 10, walkMinutes: 8, vibe: "casual", tags: ["coffee","light-lunch","outdoor","chill","quick"], popularDishes: ["Avocado Toast","Breakfast Tacos","Smoothie Bowl"], vegetarianFriendly: true, lunchHours: "7:00 AM - 6:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Cenote+Cesar+Chavez+Austin+TX", description: "Chill coffee shop with great light bites." },
  { id: "paperboy", name: "Paperboy", address: "1203 E 6th St", cuisine: "American", price: 14, walkMinutes: 5, vibe: "casual", tags: ["brunch","healthy","instagram","outdoor"], popularDishes: ["Grain Bowl","Breakfast Sandwich","Acai Bowl"], vegetarianFriendly: true, lunchHours: "8:00 AM - 3:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Paperboy+Austin+TX", description: "Healthy brunch vibes in a gorgeous outdoor space." },
  { id: "veracruz-all-natural", name: "Veracruz All Natural", address: "1704 E Cesar Chavez St", cuisine: "Mexican", price: 10, walkMinutes: 10, vibe: "food-truck", tags: ["tacos","fresh","authentic","cheap","quick"], popularDishes: ["Migas Taco","Green Salsa Chicken","Agua Frescas"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Veracruz+All+Natural+Cesar+Chavez+Austin+TX", description: "Famous migas tacos and fresh salsas from a beloved truck." },
  { id: "pueblo-viejo", name: "Pueblo Viejo", address: "1600 E Cesar Chavez St", cuisine: "Mexican", price: 9, walkMinutes: 9, vibe: "food-truck", tags: ["tacos","street-food","authentic","cheap","quick"], popularDishes: ["Barbacoa Taco","Breakfast Taco","Torta"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Pueblo+Viejo+Austin+TX", description: "Beloved East Austin taco truck with killer barbacoa." },
  { id: "salt-and-time", name: "Salt & Time", address: "1912 E 7th St", cuisine: "Italian", price: 16, walkMinutes: 12, vibe: "casual", tags: ["charcuterie","sandwiches","quality","sit-down"], popularDishes: ["Meatball Sub","Salumi Board","Italian Sandwich"], vegetarianFriendly: false, lunchHours: "11:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Salt+and+Time+Austin+TX", description: "Butcher shop with killer sandwiches and salumi." },
  { id: "counter-cafe", name: "Counter Cafe", address: "1105 W Lynn St", cuisine: "American", price: 13, walkMinutes: 20, vibe: "casual", tags: ["breakfast","comfort","classic","hearty"], popularDishes: ["Buttermilk Pancakes","Chicken Fried Steak","Burger"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Counter+Cafe+Austin+TX", description: "Classic American diner breakfast done perfectly." },
  { id: "eastside-king", name: "Eastside King", address: "1618 E 6th St", cuisine: "Thai", price: 12, walkMinutes: 8, vibe: "food-truck", tags: ["street-food","bold-flavors","creative","quick"], popularDishes: ["Thai Chicken Karaage","Beet Home Fries","Green Papaya Salad"], vegetarianFriendly: true, lunchHours: "11:30 AM - 10:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Eastside+King+Austin+TX", description: "Thai-inspired street food from a James Beard chef." },
  { id: "patrizis", name: "Patrizi's", address: "2307 Manor Rd", cuisine: "Italian", price: 14, walkMinutes: 15, vibe: "casual", tags: ["pasta","comfort","outdoor","cheap"], popularDishes: ["Cacio e Pepe","Bolognese","Burrata Salad"], vegetarianFriendly: true, lunchHours: "5:00 PM - 10:00 PM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Patrizi's+Austin+TX", description: "Cash-only pasta truck with Austin's best cacio e pepe." },
  { id: "sour-duck-market", name: "Sour Duck Market", address: "1814 E MLK Jr Blvd", cuisine: "Cafe", price: 13, walkMinutes: 14, vibe: "casual", tags: ["bakery","brunch","healthy","coffee","chill"], popularDishes: ["Sourdough Croissant","Brisket Sandwich","Pastry Box"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Sour+Duck+Market+Austin+TX", description: "Gorgeous bakery with artisan pastries and sandwiches." },
  { id: "cuantos-tacos", name: "Cuantos Tacos", address: "1108 E 12th St", cuisine: "Mexican", price: 8, walkMinutes: 10, vibe: "food-truck", tags: ["tacos","street-food","cheap","quick","authentic"], popularDishes: ["Birria Taco","Campechano","Loaded Fries"], vegetarianFriendly: false, lunchHours: "10:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Cuantos+Tacos+Austin+TX", description: "Birria tacos and loaded fries that go hard." },
  { id: "buzz-mill", name: "Buzz Mill Coffee", address: "1505 Town Creek Dr", cuisine: "Cafe", price: 10, walkMinutes: 10, vibe: "casual", tags: ["coffee","light-lunch","chill","outdoor","cheap"], popularDishes: ["Cold Brew","Breakfast Tacos","Pastries"], vegetarianFriendly: true, lunchHours: "6:00 AM - 12:00 AM", rating: 4.2, googleMapsUrl: "https://maps.google.com/?q=Buzz+Mill+Coffee+Austin+TX", description: "24-hour-ish coffee shop with great outdoor vibes." },
  { id: "flyrite", name: "Flyrite Chicken", address: "1429 E Cesar Chavez St", cuisine: "American", price: 12, walkMinutes: 8, vibe: "casual", tags: ["chicken","quick","comfort","cheap"], popularDishes: ["Fried Chicken Sandwich","Tenders","Waffle Fries"], vegetarianFriendly: false, lunchHours: "11:00 AM - 10:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Flyrite+Chicken+Austin+TX", description: "Fast-casual fried chicken done right." },
  { id: "mi-madre", name: "Mi Madre's", address: "2201 Manor Rd", cuisine: "Tex-Mex", price: 11, walkMinutes: 13, vibe: "casual", tags: ["breakfast","classic","comfort","cheap","hearty"], popularDishes: ["Enchiladas","Chilaquiles","Huevos Rancheros"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Mi+Madres+Austin+TX", description: "Old-school Tex-Mex with killer enchiladas." },
  { id: "swedish-hill", name: "Swedish Hill", address: "1137 E 11th St", cuisine: "Cafe", price: 14, walkMinutes: 10, vibe: "casual", tags: ["bakery","coffee","healthy","instagram","outdoor"], popularDishes: ["Cardamom Bun","Avocado Toast","Salmon Sandwich"], vegetarianFriendly: true, lunchHours: "7:00 AM - 5:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Swedish+Hill+Austin+TX", description: "Scandinavian-inspired bakery with amazing pastries." },
  { id: "vacancy-brewing", name: "Vacancy Brewing", address: "415 Colorado St", cuisine: "American", price: 15, walkMinutes: 15, vibe: "casual", tags: ["burgers","bar-food","outdoor","chill"], popularDishes: ["Brewery Burger","Loaded Tots","Beer Flight"], vegetarianFriendly: true, lunchHours: "11:00 AM - 11:00 PM", rating: 4.2, googleMapsUrl: "https://maps.google.com/?q=Vacancy+Brewing+Austin+TX", description: "Craft brewery with solid pub grub." },
  { id: "p-terrys", name: "P. Terry's", address: "404 S Lamar Blvd", cuisine: "Burgers", price: 8, walkMinutes: 25, vibe: "fast-food", tags: ["burgers","quick","cheap","drive-thru","classic"], popularDishes: ["#1 Burger","Double Burger","Fries & Shake"], vegetarianFriendly: true, lunchHours: "11:00 AM - 11:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=P+Terrys+S+Lamar+Austin+TX", description: "Austin's favorite burger chain. Fast, cheap, fresh." },
  { id: "torchys-tacos", name: "Torchy's Tacos", address: "1311 S 1st St", cuisine: "Mexican", price: 11, walkMinutes: 25, vibe: "casual", tags: ["tacos","creative","quick","shareable"], popularDishes: ["Trailer Park","Democrat","Green Chile Queso"], vegetarianFriendly: true, lunchHours: "8:00 AM - 10:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Torchys+Tacos+S+1st+Austin+TX", description: "Damn good tacos with creative combos." },
  { id: "tacodeli", name: "Tacodeli", address: "1500 Spyglass Dr", cuisine: "Mexican", price: 10, walkMinutes: 30, vibe: "casual", tags: ["tacos","breakfast","fresh","healthy","quick"], popularDishes: ["The Otto","Freakin Vegan","Jess Special"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Tacodeli+Austin+TX", description: "Fresh upscale tacos that started the Austin taco craze." },
  { id: "chilantro", name: "Chi'Lantro BBQ", address: "1509 S Congress Ave", cuisine: "Korean-Mexican", price: 12, walkMinutes: 30, vibe: "food-truck", tags: ["fusion","street-food","creative","quick"], popularDishes: ["Kimchi Fries","OG Burritos","Korean Short Rib"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=ChiLantro+BBQ+Austin+TX", description: "Korean-Mexican fusion that became an Austin legend." },
  { id: "taquero-mucho", name: "Taquero Mucho", address: "1515 S Congress Ave", cuisine: "Mexican", price: 12, walkMinutes: 28, vibe: "casual", tags: ["tacos","margaritas","instagram","sit-down"], popularDishes: ["Puffy Tacos","Street Corn","Birria Tacos"], vegetarianFriendly: true, lunchHours: "11:00 AM - 10:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Taquero+Mucho+Austin+TX", description: "Pink-walled taqueria with killer puffy tacos." },
  { id: "halal-bros", name: "Halal Bros", address: "2404 E Cesar Chavez St", cuisine: "Mediterranean", price: 10, walkMinutes: 15, vibe: "casual", tags: ["quick","cheap","hearty","street-food"], popularDishes: ["Chicken Shawarma Plate","Falafel Wrap","Gyro"], vegetarianFriendly: true, lunchHours: "11:00 AM - 2:00 AM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Halal+Bros+Austin+TX", description: "Cheap and huge Mediterranean plates, open late." },
  { id: "pho-phong-luu", name: "Pho Phong Luu", address: "8557 Research Blvd", cuisine: "Vietnamese", price: 11, walkMinutes: 35, vibe: "casual", tags: ["pho","noodles","cheap","warm","authentic"], popularDishes: ["Pho Tai","Bun Bo Hue","Banh Mi"], vegetarianFriendly: true, lunchHours: "10:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Pho+Phong+Luu+Austin+TX", description: "Best pho in Austin, worth the drive." },
  { id: "tumble-22", name: "Tumble 22", address: "1520 E 6th St", cuisine: "American", price: 13, walkMinutes: 7, vibe: "casual", tags: ["chicken","spicy","quick","comfort"], popularDishes: ["Hot Chicken Sandwich","Tenders","Mac & Cheese"], vegetarianFriendly: false, lunchHours: "11:00 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Tumble+22+E+6th+Austin+TX", description: "Nashville-style hot chicken that brings the heat." },
  { id: "whataburger", name: "Whataburger", address: "601 E Cesar Chavez St", cuisine: "Burgers", price: 8, walkMinutes: 12, vibe: "fast-food", tags: ["burgers","quick","cheap","classic","drive-thru"], popularDishes: ["Whataburger","Patty Melt","Honey BBQ Chicken Strip Sandwich"], vegetarianFriendly: false, lunchHours: "Open 24 hours", rating: 4.0, googleMapsUrl: "https://maps.google.com/?q=Whataburger+Cesar+Chavez+Austin+TX", description: "Texas fast food icon. Always there for you, 24/7." },
  { id: "raising-canes", name: "Raising Cane's", address: "517 E Riverside Dr", cuisine: "American", price: 10, walkMinutes: 30, vibe: "fast-food", tags: ["chicken","quick","cheap","comfort"], popularDishes: ["The Box Combo","Chicken Fingers","Cane's Sauce"], vegetarianFriendly: false, lunchHours: "10:00 AM - 1:00 AM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Raising+Canes+Riverside+Austin+TX", description: "One thing done perfectly: chicken fingers and that sauce." },
  { id: "bouldin-creek-cafe", name: "Bouldin Creek Cafe", address: "1900 S 1st St", cuisine: "Vegetarian", price: 13, walkMinutes: 28, vibe: "casual", tags: ["vegetarian","breakfast","comfort","chill","healthy"], popularDishes: ["Hippie Scramble","Veggie Burger","Tofu Migas"], vegetarianFriendly: true, lunchHours: "8:00 AM - 3:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Bouldin+Creek+Cafe+Austin+TX", description: "Austin's beloved vegetarian diner with huge portions." },
  { id: "rositas-al-pastor", name: "Rosita's Al Pastor", address: "1911 E 7th St", cuisine: "Mexican", price: 9, walkMinutes: 12, vibe: "food-truck", tags: ["tacos","street-food","authentic","cheap","quick"], popularDishes: ["Al Pastor Taco","Suadero","Campechano"], vegetarianFriendly: false, lunchHours: "6:00 PM - 2:00 AM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Rositas+Al+Pastor+Austin+TX", description: "Real-deal trompo al pastor, late-night favorite." },
  { id: "popeyes", name: "Popeyes", address: "1120 E 7th St", cuisine: "American", price: 9, walkMinutes: 8, vibe: "fast-food", tags: ["chicken","quick","cheap","comfort","drive-thru"], popularDishes: ["Chicken Sandwich","Spicy Tenders","Red Beans & Rice"], vegetarianFriendly: false, lunchHours: "10:00 AM - 11:00 PM", rating: 3.9, googleMapsUrl: "https://maps.google.com/?q=Popeyes+E+7th+Austin+TX", description: "That chicken sandwich. You know the one." },
  { id: "phoebe", name: "Phoebe's Diner", address: "815 W 47th St", cuisine: "American", price: 13, walkMinutes: 35, vibe: "casual", tags: ["breakfast","comfort","hearty","classic"], popularDishes: ["Country Fried Steak","Biscuits & Gravy","Pancakes"], vegetarianFriendly: true, lunchHours: "7:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Phoebes+Diner+Austin+TX", description: "Retro diner with all-day breakfast and huge portions." },
  { id: "con-todo", name: "Con Todo", address: "2027 E Cesar Chavez St", cuisine: "Mexican", price: 10, walkMinutes: 12, vibe: "food-truck", tags: ["tacos","street-food","authentic","cheap","quick"], popularDishes: ["Birria Quesotaco","Al Pastor Taco","Horchata"], vegetarianFriendly: true, lunchHours: "8:00 AM - 3:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Con+Todo+Austin+TX", description: "Birria specialists with perfectly crispy quesotacos." },
  { id: "little-deli", name: "Little Deli & Pizzeria", address: "7101 Woodrow Ave", cuisine: "Pizza", price: 11, walkMinutes: 35, vibe: "casual", tags: ["pizza","sandwiches","cheap","classic","comfort"], popularDishes: ["NY-Style Slice","Meatball Sub","Pepperoni Pizza"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Little+Deli+Pizzeria+Austin+TX", description: "Best NY-style pizza by the slice in Austin." },
  { id: "seoulju", name: "Seoulju Korean BBQ", address: "2400 E Cesar Chavez St", cuisine: "Korean", price: 15, walkMinutes: 15, vibe: "casual", tags: ["bbq","shareable","fun","sit-down"], popularDishes: ["Bulgogi","Korean Fried Chicken","Bibimbap"], vegetarianFriendly: true, lunchHours: "11:00 AM - 10:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Seoulju+Korean+Austin+TX", description: "Affordable Korean BBQ with tabletop grills." },
  { id: "wow-poke", name: "Wow Poke", address: "1009 E Cesar Chavez St", cuisine: "Hawaiian", price: 14, walkMinutes: 8, vibe: "casual", tags: ["poke","healthy","fresh","quick","light-lunch"], popularDishes: ["Build Your Own Bowl","Spicy Tuna Bowl","Salmon Avocado Bowl"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Wow+Poke+Austin+TX", description: "Fresh poke bowls with quality fish and tons of toppings." },
  { id: "clay-pit", name: "Clay Pit", address: "1601 Guadalupe St", cuisine: "Indian", price: 14, walkMinutes: 20, vibe: "casual", tags: ["curry","lunch-buffet","vegetarian","sit-down","hearty"], popularDishes: ["Lunch Buffet","Chicken Tikka Masala","Garlic Naan"], vegetarianFriendly: true, lunchHours: "11:00 AM - 2:30 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Clay+Pit+Austin+TX", description: "Indian lunch buffet that's an insane deal." },
  { id: "bombay-dhaba", name: "Bombay Dhaba", address: "2107 E Cesar Chavez St", cuisine: "Indian", price: 11, walkMinutes: 13, vibe: "food-truck", tags: ["curry","street-food","cheap","quick","authentic"], popularDishes: ["Butter Chicken","Samosa Chaat","Tikka Wrap"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Bombay+Dhaba+Austin+TX", description: "Legit Indian street food from a truck on Cesar Chavez." },
  { id: "pupuseria-chapina", name: "Pupuseria Chapina", address: "2000 E 7th St", cuisine: "Salvadoran", price: 9, walkMinutes: 12, vibe: "casual", tags: ["pupusas","authentic","cheap","comfort","hearty"], popularDishes: ["Pupusas Revueltas","Platano con Crema","Tamales"], vegetarianFriendly: true, lunchHours: "8:00 AM - 8:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Pupuseria+Chapina+Austin+TX", description: "Handmade pupusas that are worth every penny." },
  { id: "arpeggio-grill", name: "Arpeggio Grill", address: "6619 Airport Blvd", cuisine: "Mediterranean", price: 12, walkMinutes: 35, vibe: "casual", tags: ["kebab","healthy","cheap","authentic","hearty"], popularDishes: ["Chicken Shawarma Plate","Lamb Kebab","Hummus Platter"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.6, googleMapsUrl: "https://maps.google.com/?q=Arpeggio+Grill+Austin+TX", description: "Best Mediterranean in Austin. Huge portions, tiny price." },
  { id: "pluckers", name: "Pluckers Wing Bar", address: "2222 Rio Grande St", cuisine: "Wings", price: 15, walkMinutes: 25, vibe: "casual", tags: ["wings","bar-food","shareable","spicy","fun"], popularDishes: ["Fried Pickles","Baker's Dozen Wings","Loaded Waffle Fries"], vegetarianFriendly: false, lunchHours: "11:00 AM - 12:00 AM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Pluckers+Wing+Bar+Austin+TX", description: "Austin's wing institution. 25+ flavors." },
  { id: "wingstop", name: "Wingstop", address: "1200 E 7th St", cuisine: "Wings", price: 10, walkMinutes: 8, vibe: "fast-food", tags: ["wings","quick","cheap","spicy","comfort"], popularDishes: ["Lemon Pepper Wings","Cajun Wings","Fries"], vegetarianFriendly: false, lunchHours: "10:30 AM - 12:00 AM", rating: 3.9, googleMapsUrl: "https://maps.google.com/?q=Wingstop+E+7th+Austin+TX", description: "Fast wings with every flavor you can imagine." },
  { id: "quality-seafood", name: "Quality Seafood", address: "5621 Airport Blvd", cuisine: "Seafood", price: 15, walkMinutes: 35, vibe: "casual", tags: ["seafood","fried","classic","hearty","sit-down"], popularDishes: ["Fried Shrimp Plate","Oyster Po'Boy","Gumbo"], vegetarianFriendly: false, lunchHours: "10:30 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Quality+Seafood+Austin+TX", description: "Old-school seafood market with killer fried baskets." },
  { id: "thundercloud-subs", name: "Thundercloud Subs", address: "1608 Lavaca St", cuisine: "Sandwiches", price: 8, walkMinutes: 18, vibe: "casual", tags: ["sandwiches","quick","cheap","classic","healthy"], popularDishes: ["California Club","NY Italian","Office Favorite"], vegetarianFriendly: true, lunchHours: "7:00 AM - 8:00 PM", rating: 4.2, googleMapsUrl: "https://maps.google.com/?q=Thundercloud+Subs+Lavaca+Austin+TX", description: "Austin's own sub chain since 1975. Keep it local." },
  { id: "which-wich", name: "Which Wich", address: "1900 E MLK Jr Blvd", cuisine: "Sandwiches", price: 10, walkMinutes: 14, vibe: "casual", tags: ["sandwiches","quick","customizable","cheap"], popularDishes: ["Wicked","Thank You Turkey","Gyro"], vegetarianFriendly: true, lunchHours: "10:30 AM - 9:00 PM", rating: 4.0, googleMapsUrl: "https://maps.google.com/?q=Which+Wich+MLK+Austin+TX", description: "Build your own sandwich. Bag system is a vibe." },
  { id: "taste-of-ethiopia", name: "Taste of Ethiopia", address: "1100 Grand Avenue Pkwy", cuisine: "Ethiopian", price: 14, walkMinutes: 35, vibe: "casual", tags: ["ethiopian","unique","vegetarian","shareable","authentic"], popularDishes: ["Combo Platter","Doro Wat","Vegetarian Sampler"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Taste+of+Ethiopia+Austin+TX", description: "Eat with your hands. Injera and stews done right." },
  { id: "shanghai-noodle", name: "Shanghai Noodle House", address: "10901 N Lamar Blvd", cuisine: "Chinese", price: 12, walkMinutes: 35, vibe: "casual", tags: ["noodles","dumplings","authentic","cheap","warm"], popularDishes: ["Soup Dumplings","Dan Dan Noodles","Scallion Pancakes"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:30 PM", rating: 4.5, googleMapsUrl: "https://maps.google.com/?q=Shanghai+Noodle+House+Austin+TX", description: "Soup dumplings worth the drive. Cash only." },
  { id: "ms-ps", name: "Ms. P's Electric Cock", address: "1900 E 12th St", cuisine: "Thai", price: 13, walkMinutes: 14, vibe: "casual", tags: ["thai","spicy","creative","sit-down","bold-flavors"], popularDishes: ["Pad Thai","Green Curry","Thai Iced Tea"], vegetarianFriendly: true, lunchHours: "11:00 AM - 9:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Ms+Ps+Electric+Cock+Austin+TX", description: "Funky Thai spot with legit curries and noodles." },
  { id: "grannys-tacos", name: "Granny's Tacos", address: "1704 E 7th St", cuisine: "Mexican", price: 8, walkMinutes: 10, vibe: "food-truck", tags: ["tacos","breakfast","cheap","quick","authentic"], popularDishes: ["Breakfast Taco","Bean & Cheese","Barbacoa"], vegetarianFriendly: true, lunchHours: "6:00 AM - 2:00 PM", rating: 4.3, googleMapsUrl: "https://maps.google.com/?q=Grannys+Tacos+Austin+TX", description: "No-frills breakfast tacos for under $3 each." },
  { id: "santis-ices", name: "Santi's Ices & Eats", address: "2207 E Cesar Chavez St", cuisine: "Mexican", price: 8, walkMinutes: 14, vibe: "food-truck", tags: ["street-food","cheap","quick","light-lunch"], popularDishes: ["Elote","Mangonada","Tostilocos"], vegetarianFriendly: true, lunchHours: "10:00 AM - 8:00 PM", rating: 4.4, googleMapsUrl: "https://maps.google.com/?q=Santis+Ices+Eats+Austin+TX", description: "Mexican street snacks and frozen treats." },
  { id: "the-league", name: "The League Kitchen & Tavern", address: "75 Rainey St", cuisine: "American", price: 15, walkMinutes: 18, vibe: "casual", tags: ["burgers","bar-food","outdoor","shareable","fun"], popularDishes: ["League Burger","Chicken Tenders","Loaded Nachos"], vegetarianFriendly: true, lunchHours: "11:00 AM - 12:00 AM", rating: 4.2, googleMapsUrl: "https://maps.google.com/?q=The+League+Kitchen+Rainey+Austin+TX", description: "Sports bar on Rainey with solid burgers and tons of TVs." },
];

export const cuisines = [...new Set(restaurants.map(r => r.cuisine))];

export const cuisineColors = {
  'BBQ': '#f97316', 'Mexican': '#22c55e', 'Pizza': '#ef4444',
  'Japanese': '#ec4899', 'Caribbean': '#14b8a6', 'Japanese-BBQ': '#f43f5e',
  'Italian': '#a855f7', 'Tex-Mex': '#eab308', 'American': '#3b82f6',
  'Argentine': '#06b6d4', 'Filipino': '#f59e0b', 'Chinese': '#e11d48',
  'Cafe': '#84cc16', 'Asian-BBQ': '#d946ef', 'Thai': '#10b981',
  'Burgers': '#f97316', 'Korean-Mexican': '#ec4899', 'Mediterranean': '#14b8a6',
  'Vietnamese': '#06b6d4', 'Vegetarian': '#22c55e', 'Korean': '#e11d48',
  'Hawaiian': '#3b82f6', 'Indian': '#f59e0b', 'Salvadoran': '#a855f7',
  'Wings': '#ef4444', 'Seafood': '#06b6d4', 'Sandwiches': '#84cc16',
  'Ethiopian': '#eab308',
};

export function getCuisineColor(cuisine) {
  return cuisineColors[cuisine] || '#ff6b35';
}

export function getRandom(arr = restaurants) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
