export const restaurants = [
  {"id":"via-313","name":"Via 313","address":"1802 E 6th St","cuisine":"Pizza","price":16,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["cheesy","detroit-style","comfort","shareable"],"popularDishes":["The Detroiter","Cadillac","The Marinara"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 11:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Via+313+East+6th+Austin+TX","description":"Detroit-style deep dish pizza with crispy cheese edges."},
  {"id":"ramen-tatsuya","name":"Ramen Tatsu-ya","address":"1600 E 6th St","cuisine":"Japanese","price":17,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats, Favor","tags":["ramen","umami","cozy","warm"],"popularDishes":["Original Tonkotsu","Vegan Ramen","Underbelly"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.7,"googleMapsUrl":"https://maps.google.com/?q=Ramen+Tatsu-ya+E+6th+Austin+TX","description":"Austin's best ramen, no debate."},
  {"id":"joes-bakery","name":"Joe's Bakery","address":"2305 E 7th St","cuisine":"Tex-Mex","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","comfort","classic","cheap"],"popularDishes":["Migas Plate","Carne Guisada","Puffy Tacos"],"vegetarianFriendly":true,"lunchHours":"6:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Joe's+Bakery+Austin+TX","description":"Old-school Tex-Mex breakfast & lunch institution."},
  {"id":"juan-in-a-million","name":"Juan in a Million","address":"2300 E Cesar Chavez St","cuisine":"Tex-Mex","price":9,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","tacos","classic","cheap","hearty"],"popularDishes":["Don Juan Taco","Carne Guisada","Barbacoa"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Juan+in+a+Million+Austin+TX","description":"Home of the famous Don Juan breakfast taco."},
  {"id":"el-pollo-rey","name":"El Pollo Rey","address":"2209 E Cesar Chavez St","cuisine":"Mexican","price":11,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["grilled-chicken","quick","authentic","cheap"],"popularDishes":["Whole Grilled Chicken","Chicken Plate","Tacos"],"vegetarianFriendly":false,"lunchHours":"10:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=El+Pollo+Rey+Austin+TX","description":"Perfectly grilled chicken, no frills."},
  {"id":"buenos-aires-cafe","name":"Buenos Aires Cafe","address":"1201 E 6th St","cuisine":"Argentine","price":18,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["empanadas","steak","south-american","cozy"],"popularDishes":["Empanadas","Milanesa","Grilled Steak"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Buenos+Aires+Cafe+Austin+TX","description":"Authentic Argentine food, closest to the office."},
  {"id":"tamale-house-east","name":"Tamale House East","address":"1707 E 6th St","cuisine":"Tex-Mex","price":9,"deliveryMinutes":5,"deliveryApps":"DoorDash, Favor","tags":["tamales","breakfast","classic","cheap","quick"],"popularDishes":["Tamales","Migas Taco","Carne Guisada Plate"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 2:30 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Tamale+House+East+Austin+TX","description":"East Austin tamale institution since forever."},
  {"id":"revelry","name":"Revelry Kitchen + Bar","address":"1410 E 6th St","cuisine":"American","price":15,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","chill"],"popularDishes":["Smash Burger","Chicken Sandwich","Fries"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 12:00 AM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Revelry+Kitchen+Bar+Austin+TX","description":"Solid burgers and chill patio vibes."},
  {"id":"li-neighborhood","name":"Li Neighborhood Noodles","address":"1900 E 6th St","cuisine":"Chinese","price":12,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats","tags":["noodles","hand-pulled","authentic","cheap","warm"],"popularDishes":["Biang Biang Noodles","Lamb Burger","Cold Noodles"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Li+Neighborhood+Noodles+Austin+TX","description":"Hand-pulled noodles and authentic Xi'an flavors."},
  {"id":"paperboy","name":"Paperboy","address":"1203 E 6th St","cuisine":"American","price":14,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["brunch","healthy","instagram","outdoor"],"popularDishes":["Grain Bowl","Breakfast Sandwich","Acai Bowl"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Paperboy+Austin+TX","description":"Healthy brunch vibes in a gorgeous outdoor space."},
  {"id":"salt-and-time","name":"Salt & Time","address":"1912 E 7th St","cuisine":"Italian","price":16,"deliveryMinutes":7,"deliveryApps":"DoorDash, Favor","tags":["charcuterie","sandwiches","quality","sit-down"],"popularDishes":["Meatball Sub","Salumi Board","Italian Sandwich"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Salt+and+Time+Austin+TX","description":"Butcher shop with killer sandwiches and salumi."},
  {"id":"patrizis","name":"Patrizi's","address":"2307 Manor Rd","cuisine":"Italian","price":14,"deliveryMinutes":9,"deliveryApps":"DoorDash, Favor","tags":["pasta","comfort","outdoor","cheap"],"popularDishes":["Cacio e Pepe","Bolognese","Burrata Salad"],"vegetarianFriendly":true,"lunchHours":"5:00 PM - 10:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Patrizi's+Austin+TX","description":"Austin's best cacio e pepe. Worth every penny."},
  {"id":"sour-duck-market","name":"Sour Duck Market","address":"1814 E MLK Jr Blvd","cuisine":"Cafe","price":13,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["bakery","brunch","healthy","coffee","chill"],"popularDishes":["Sourdough Croissant","Brisket Sandwich","Pastry Box"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Sour+Duck+Market+Austin+TX","description":"Gorgeous bakery with artisan pastries and sandwiches."},
  {"id":"flyrite","name":"Flyrite Chicken","address":"1429 E Cesar Chavez St","cuisine":"American","price":12,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","quick","comfort","cheap"],"popularDishes":["Fried Chicken Sandwich","Tenders","Waffle Fries"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Flyrite+Chicken+Austin+TX","description":"Fast-casual fried chicken done right."},
  {"id":"mi-madre","name":"Mi Madre's","address":"2201 Manor Rd","cuisine":"Tex-Mex","price":11,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","classic","comfort","cheap","hearty"],"popularDishes":["Enchiladas","Chilaquiles","Huevos Rancheros"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Mi+Madres+Austin+TX","description":"Old-school Tex-Mex with killer enchiladas."},
  {"id":"swedish-hill","name":"Swedish Hill","address":"1137 E 11th St","cuisine":"Cafe","price":14,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats","tags":["bakery","coffee","healthy","instagram","outdoor"],"popularDishes":["Cardamom Bun","Avocado Toast","Salmon Sandwich"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 5:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Swedish+Hill+Austin+TX","description":"Scandinavian-inspired bakery with amazing pastries."},
  {"id":"vacancy-brewing","name":"Vacancy Brewing","address":"415 Colorado St","cuisine":"American","price":15,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","chill"],"popularDishes":["Brewery Burger","Loaded Tots","Beer Flight"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 11:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Vacancy+Brewing+Austin+TX","description":"Craft brewery with solid pub grub."},
  {"id":"halal-bros","name":"Halal Bros","address":"2404 E Cesar Chavez St","cuisine":"Mediterranean","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats, Favor","tags":["quick","cheap","hearty","street-food"],"popularDishes":["Chicken Shawarma Plate","Falafel Wrap","Gyro"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 2:00 AM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Halal+Bros+Austin+TX","description":"Cheap and huge Mediterranean plates, open late."},
  {"id":"tumble-22","name":"Tumble 22","address":"1520 E 6th St","cuisine":"American","price":13,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","spicy","quick","comfort"],"popularDishes":["Hot Chicken Sandwich","Tenders","Mac & Cheese"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Tumble+22+E+6th+Austin+TX","description":"Nashville-style hot chicken that brings the heat."},
  {"id":"whataburger","name":"Whataburger","address":"601 E Cesar Chavez St","cuisine":"Burgers","price":8,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats, Favor","tags":["burgers","quick","cheap","classic","drive-thru"],"popularDishes":["Whataburger","Patty Melt","Honey BBQ Chicken Strip Sandwich"],"vegetarianFriendly":false,"lunchHours":"Open 24 hours","rating":4,"googleMapsUrl":"https://maps.google.com/?q=Whataburger+Cesar+Chavez+Austin+TX","description":"Texas fast food icon. Always there for you, 24/7."},
  {"id":"popeyes","name":"Popeyes","address":"1120 E 7th St","cuisine":"American","price":9,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","quick","cheap","comfort","drive-thru"],"popularDishes":["Chicken Sandwich","Spicy Tenders","Red Beans & Rice"],"vegetarianFriendly":false,"lunchHours":"10:00 AM - 11:00 PM","rating":3.9,"googleMapsUrl":"https://maps.google.com/?q=Popeyes+E+7th+Austin+TX","description":"That chicken sandwich. You know the one."},
  {"id":"seoulju","name":"Seoulju Korean BBQ","address":"2400 E Cesar Chavez St","cuisine":"Korean","price":15,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["bbq","shareable","fun","sit-down"],"popularDishes":["Bulgogi","Korean Fried Chicken","Bibimbap"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Seoulju+Korean+Austin+TX","description":"Affordable Korean BBQ with tabletop grills."},
  {"id":"wow-poke","name":"Wow Poke","address":"1009 E Cesar Chavez St","cuisine":"Hawaiian","price":14,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["poke","healthy","fresh","quick","light-lunch"],"popularDishes":["Build Your Own Bowl","Spicy Tuna Bowl","Salmon Avocado Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Wow+Poke+Austin+TX","description":"Fresh poke bowls with quality fish and tons of toppings."},
  {"id":"pupuseria-chapina","name":"Pupuseria Chapina","address":"2000 E 7th St","cuisine":"Salvadoran","price":9,"deliveryMinutes":7,"deliveryApps":"DoorDash, Favor","tags":["pupusas","authentic","cheap","comfort","hearty"],"popularDishes":["Pupusas Revueltas","Platano con Crema","Tamales"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 8:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Pupuseria+Chapina+Austin+TX","description":"Handmade pupusas that are worth every penny."},
  {"id":"wingstop","name":"Wingstop","address":"1200 E 7th St","cuisine":"Wings","price":10,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats, Wingstop App","tags":["wings","quick","cheap","spicy","comfort"],"popularDishes":["Lemon Pepper Wings","Cajun Wings","Fries"],"vegetarianFriendly":false,"lunchHours":"10:30 AM - 12:00 AM","rating":3.9,"googleMapsUrl":"https://maps.google.com/?q=Wingstop+E+7th+Austin+TX","description":"Fast wings with every flavor you can imagine."},
  {"id":"thundercloud-subs","name":"Thundercloud Subs","address":"1608 Lavaca St","cuisine":"Sandwiches","price":8,"deliveryMinutes":10,"deliveryApps":"DoorDash, Favor","tags":["sandwiches","quick","cheap","classic","healthy"],"popularDishes":["California Club","NY Italian","Office Favorite"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 8:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Thundercloud+Subs+Lavaca+Austin+TX","description":"Austin's own sub chain since 1975. Keep it local."},
  {"id":"which-wich","name":"Which Wich","address":"1900 E MLK Jr Blvd","cuisine":"Sandwiches","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["sandwiches","quick","customizable","cheap"],"popularDishes":["Wicked","Thank You Turkey","Gyro"],"vegetarianFriendly":true,"lunchHours":"10:30 AM - 9:00 PM","rating":4,"googleMapsUrl":"https://maps.google.com/?q=Which+Wich+MLK+Austin+TX","description":"Build your own sandwich. Bag system is a vibe."},
  {"id":"ms-ps","name":"Ms. P's Electric Cock","address":"1900 E 12th St","cuisine":"Thai","price":13,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["thai","spicy","creative","sit-down","bold-flavors"],"popularDishes":["Pad Thai","Green Curry","Thai Iced Tea"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Ms+Ps+Electric+Cock+Austin+TX","description":"Funky Thai spot with legit curries and noodles."},
  {"id":"the-league","name":"The League Kitchen","address":"75 Rainey St","cuisine":"American","price":15,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","shareable","fun"],"popularDishes":["League Burger","Chicken Tenders","Loaded Nachos"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 12:00 AM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=The+League+Kitchen+Rainey+Austin+TX","description":"Sports bar on Rainey with solid burgers and tons of TVs."},
  {"id":"suerte","name":"Suerte","address":"1800 E 6th St","cuisine":"Mexican","price":25,"deliveryMinutes":6,"deliveryApps":"DoorDash, Caviar","tags":["contemporary","creative","date-spot","sit-down"],"popularDishes":["Suadero Tacos","Duck Carnitas","Mole"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 2:30 PM","rating":4.8,"googleMapsUrl":"https://maps.google.com/?q=Suerte+Austin+TX","description":"Contemporary Mexican with masa-focused menu."},
  {"id":"canje","name":"Canje","address":"1914 E 6th St","cuisine":"Caribbean","price":24,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["caribbean","creative","tropical","sit-down"],"popularDishes":["Jerk Chicken","Curry Goat","Plantain Chips"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 2:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Canje+Austin+TX","description":"Caribbean flavors with fine dining technique."},
  {"id":"launderette","name":"Launderette","address":"2115 Holly St","cuisine":"American","price":22,"deliveryMinutes":9,"deliveryApps":"DoorDash, UberEats","tags":["brunch","creative","instagram","sit-down"],"popularDishes":["Wagyu Burger","Gulf Snapper","Seasonal Salads"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Launderette+Austin+TX","description":"Beautiful American cafe in a former laundromat."},
  {"id":"hillside-farmacy","name":"Hillside Farmacy","address":"1209 E 11th St","cuisine":"American","price":19,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["farm-to-table","brunch","outdoor","sit-down"],"popularDishes":["Farmacy Burger","Brisket Grilled Cheese","Seasonal Salad"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Hillside+Farmacy+Austin+TX","description":"Farm-to-table in a converted 1950s pharmacy."},
  {"id":"henbit","name":"Henbit","address":"2112 E 7th St","cuisine":"American","price":19,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["brunch","healthy","creative","outdoor"],"popularDishes":["Fried Chicken Biscuit","Grain Bowl","Pastries"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Henbit+Austin+TX","description":"Beautiful cafe with inventive brunch plates."},
  {"id":"la-barbecue","name":"La Barbecue","address":"2401 E Cesar Chavez St","cuisine":"BBQ","price":18,"deliveryMinutes":9,"deliveryApps":"DoorDash, Favor","tags":["smoky","outdoor","meat-lovers","hearty"],"popularDishes":["Brisket","Pulled Pork Sandwich","Beef Ribs"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 6:00 PM","rating":4.7,"googleMapsUrl":"https://maps.google.com/?q=La+Barbecue+Austin+TX","description":"Legendary East Austin BBQ with lines worth the wait."},
  {"id":"nixta-taqueria","name":"Nixta Taqueria","address":"2512 E 12th St","cuisine":"Mexican","price":14,"deliveryMinutes":10,"deliveryApps":"DoorDash, Favor","tags":["heirloom-corn","creative","unique","quick"],"popularDishes":["Duck Carnitas Taco","Migas Taco","Masa Fries"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 2:00 PM","rating":4.8,"googleMapsUrl":"https://maps.google.com/?q=Nixta+Taqueria+Austin+TX","description":"Heirloom corn tacos that redefine the taco game."},
  {"id":"oko","name":"OKO","address":"1308 E 6th St","cuisine":"Filipino","price":14,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["street-food","unique","bold-flavors","quick"],"popularDishes":["Sisig","Lumpia","Adobo Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=OKO+Filipino+Austin+TX","description":"Filipino street food with big bold flavors."}
];

export const cuisines = [...new Set(restaurants.map(r => r.cuisine))];

export const cuisineColors = {
  'BBQ': '#f97316', 'Mexican': '#22c55e', 'Pizza': '#ef4444',
  'Japanese': '#ec4899', 'Caribbean': '#14b8a6',
  'Italian': '#a855f7', 'Tex-Mex': '#eab308', 'American': '#3b82f6',
  'Argentine': '#06b6d4', 'Filipino': '#f59e0b', 'Chinese': '#e11d48',
  'Cafe': '#84cc16', 'Asian-BBQ': '#d946ef', 'Thai': '#10b981',
  'Burgers': '#f97316', 'Korean-Mexican': '#ec4899', 'Mediterranean': '#14b8a6',
  'Korean': '#e11d48', 'Hawaiian': '#3b82f6', 'Indian': '#f59e0b',
  'Salvadoran': '#a855f7', 'Wings': '#ef4444', 'Sandwiches': '#84cc16',
};

export function getCuisineColor(cuisine) {
  return cuisineColors[cuisine] || '#ff6b35';
}

export function getRandom(arr = restaurants) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
