export const restaurants = [
  {"id":"via-313","name":"Via 313","address":"1802 E 6th St","cuisine":"Pizza","price":16,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["cheesy","detroit-style","comfort","shareable"],"popularDishes":["The Detroiter","Cadillac","The Marinara"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 11:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Via+313+East+6th+Austin+TX","description":"Detroit-style deep dish pizza with crispy cheese edges."},
  {"id":"ramen-tatsuya","name":"Ramen Tatsu-ya","address":"1600 E 6th St","cuisine":"Japanese","price":17,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats, Favor","tags":["ramen","umami","cozy","warm"],"popularDishes":["Original Tonkotsu","Vegan Ramen","Underbelly"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.7,"googleMapsUrl":"https://maps.google.com/?q=Ramen+Tatsu-ya+E+6th+Austin+TX","description":"Austin's best ramen, no debate."},
  {"id":"joes-bakery","name":"Joe's Bakery","address":"2305 E 7th St","cuisine":"Tex-Mex","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","comfort","classic","cheap"],"popularDishes":["Migas Plate","Carne Guisada","Puffy Tacos"],"vegetarianFriendly":true,"lunchHours":"6:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Joe's+Bakery+Austin+TX","description":"Old-school Tex-Mex breakfast & lunch institution."},
  {"id":"juan-in-a-million","name":"Juan in a Million","address":"2300 E Cesar Chavez St","cuisine":"Tex-Mex","price":9,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","tacos","classic","cheap","hearty"],"popularDishes":["Don Juan Taco","Carne Guisada","Barbacoa"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Juan+in+a+Million+Austin+TX","description":"Home of the famous Don Juan breakfast taco."},
  {"id":"el-pollo-rey","name":"El Pollo Rey","address":"2209 E Cesar Chavez St","cuisine":"Mexican","price":11,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["grilled-chicken","quick","authentic","cheap"],"popularDishes":["Whole Grilled Chicken","Chicken Plate","Tacos"],"vegetarianFriendly":false,"lunchHours":"10:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=El+Pollo+Rey+Austin+TX","description":"Perfectly grilled chicken, no frills."},
  {"id":"buenos-aires-cafe","name":"Buenos Aires Cafe","address":"1201 E 6th St","cuisine":"Argentine","price":18,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["empanadas","steak","south-american","cozy"],"popularDishes":["Empanadas","Milanesa","Grilled Steak"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Buenos+Aires+Cafe+Austin+TX","description":"Authentic Argentine food, closest to the office."},
  {"id":"tamale-house-east","name":"Tamale House East","address":"1707 E 6th St","cuisine":"Tex-Mex","price":9,"deliveryMinutes":5,"deliveryApps":"DoorDash, Favor","tags":["tamales","breakfast","classic","cheap","quick"],"popularDishes":["Tamales","Migas Taco","Carne Guisada Plate"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 2:30 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Tamale+House+East+Austin+TX","description":"East Austin tamale institution since forever."},
  {"id":"revelry","name":"Revelry Kitchen + Bar","address":"1410 E 6th St","cuisine":"American","price":15,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","chill"],"popularDishes":["Smash Burger","Chicken Sandwich","Fries"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 12:00 AM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Revelry+Kitchen+Bar+Austin+TX","description":"Solid burgers and chill patio vibes."},
  {"id":"li-neighborhood","name":"Li Neighborhood Noodles","address":"1900 E 6th St","cuisine":"Chinese","price":12,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats","tags":["noodles","hand-pulled","authentic","cheap","warm"],"popularDishes":["Biang Biang Noodles","Lamb Burger","Cold Noodles"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Li+Neighborhood+Noodles+Austin+TX","description":"Hand-pulled noodles and authentic Xi'an flavors."},
  {"id":"paperboy","name":"Paperboy","address":"1203 E 6th St","cuisine":"American","price":14,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["brunch","healthy","instagram","outdoor"],"popularDishes":["Grain Bowl","Breakfast Sandwich","Acai Bowl"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Paperboy+Austin+TX","description":"Healthy brunch vibes in a gorgeous outdoor space."},
  {"id":"salt-and-time","name":"Salt & Time","address":"1912 E 7th St","cuisine":"Italian","price":16,"deliveryMinutes":7,"deliveryApps":"DoorDash, Favor","tags":["charcuterie","sandwiches","quality","sit-down"],"popularDishes":["Meatball Sub","Salumi Board","Italian Sandwich"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Salt+and+Time+Austin+TX","description":"Butcher shop with killer sandwiches and salumi."},
  {"id":"patrizis","name":"Patrizi's","address":"2307 Manor Rd","cuisine":"Italian","price":14,"deliveryMinutes":9,"deliveryApps":"DoorDash, Favor","tags":["pasta","comfort","outdoor","cheap"],"popularDishes":["Cacio e Pepe","Bolognese","Burrata Salad"],"vegetarianFriendly":true,"lunchHours":"5:00 PM - 10:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Patrizi's+Austin+TX","description":"Austin's best cacio e pepe. Worth every penny."},
  {"id":"sour-duck-market","name":"Sour Duck Market","address":"1814 E MLK Jr Blvd","cuisine":"Cafe","price":13,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["bakery","brunch","healthy","coffee","chill"],"popularDishes":["Sourdough Croissant","Brisket Sandwich","Pastry Box"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Sour+Duck+Market+Austin+TX","description":"Gorgeous bakery with artisan pastries and sandwiches."},
  {"id":"flyrite","name":"Flyrite Chicken","address":"1429 E Cesar Chavez St","cuisine":"American","price":12,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","quick","comfort","cheap"],"popularDishes":["Fried Chicken Sandwich","Tenders","Waffle Fries"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Flyrite+Chicken+Austin+TX","description":"Fast-casual fried chicken done right."},
  {"id":"mi-madre","name":"Mi Madre's","address":"2201 Manor Rd","cuisine":"Tex-Mex","price":11,"deliveryMinutes":8,"deliveryApps":"DoorDash, Favor","tags":["breakfast","classic","comfort","cheap","hearty"],"popularDishes":["Enchiladas","Chilaquiles","Huevos Rancheros"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Mi+Madres+Austin+TX","description":"Old-school Tex-Mex with killer enchiladas."},
  {"id":"swedish-hill","name":"Swedish Hill","address":"1137 E 11th St","cuisine":"Cafe","price":14,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats","tags":["bakery","coffee","healthy","instagram","outdoor"],"popularDishes":["Cardamom Bun","Avocado Toast","Salmon Sandwich"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 5:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Swedish+Hill+Austin+TX","description":"Scandinavian-inspired bakery with amazing pastries."},
  {"id":"vacancy-brewing","name":"Vacancy Brewing","address":"415 Colorado St","cuisine":"American","price":15,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","chill"],"popularDishes":["Brewery Burger","Loaded Tots","Beer Flight"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 11:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Vacancy+Brewing+Austin+TX","description":"Craft brewery with solid pub grub."},
  {"id":"halal-bros","name":"Halal Bros","address":"2404 E Cesar Chavez St","cuisine":"Mediterranean","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats, Favor","tags":["quick","cheap","hearty","street-food"],"popularDishes":["Chicken Shawarma Plate","Falafel Wrap","Gyro"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 2:00 AM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Halal+Bros+Austin+TX","description":"Cheap and huge Mediterranean plates, open late."},
  {"id":"tumble-22","name":"Tumble 22","address":"1520 E 6th St","cuisine":"American","price":13,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","spicy","quick","comfort"],"popularDishes":["Hot Chicken Sandwich","Tenders","Mac & Cheese"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Tumble+22+E+6th+Austin+TX","description":"Nashville-style hot chicken that brings the heat."},
  {"id":"whataburger","name":"Whataburger","address":"601 E Cesar Chavez St","cuisine":"Burgers","price":8,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats, Favor","tags":["burgers","quick","cheap","classic","drive-thru"],"popularDishes":["Whataburger","Patty Melt","Honey BBQ Chicken Strip Sandwich"],"vegetarianFriendly":false,"lunchHours":"Open 24 hours","rating":4,"googleMapsUrl":"https://maps.google.com/?q=Whataburger+Cesar+Chavez+Austin+TX","description":"Texas fast food icon. Always there for you, 24/7."},
  {"id":"popeyes","name":"Popeyes","address":"1120 E 7th St","cuisine":"American","price":9,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["chicken","quick","cheap","comfort","drive-thru"],"popularDishes":["Chicken Sandwich","Spicy Tenders","Red Beans & Rice"],"vegetarianFriendly":false,"lunchHours":"10:00 AM - 11:00 PM","rating":3.9,"googleMapsUrl":"https://maps.google.com/?q=Popeyes+E+7th+Austin+TX","description":"That chicken sandwich. You know the one."},
  {"id":"seoulju","name":"Seoulju Korean BBQ","address":"2400 E Cesar Chavez St","cuisine":"Korean","price":15,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["bbq","shareable","fun","sit-down"],"popularDishes":["Bulgogi","Korean Fried Chicken","Bibimbap"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Seoulju+Korean+Austin+TX","description":"Affordable Korean BBQ with tabletop grills."},
  {"id":"wow-poke","name":"Wow Poke","address":"1009 E Cesar Chavez St","cuisine":"Hawaiian","price":14,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["poke","healthy","fresh","quick","light-lunch"],"popularDishes":["Build Your Own Bowl","Spicy Tuna Bowl","Salmon Avocado Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Wow+Poke+Austin+TX","description":"Fresh poke bowls with quality fish and tons of toppings."},
  {"id":"pupuseria-chapina","name":"Pupuseria Chapina","address":"2000 E 7th St","cuisine":"Salvadoran","price":9,"deliveryMinutes":7,"deliveryApps":"DoorDash, Favor","tags":["pupusas","authentic","cheap","comfort","hearty"],"popularDishes":["Pupusas Revueltas","Platano con Crema","Tamales"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 8:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Pupuseria+Chapina+Austin+TX","description":"Handmade pupusas that are worth every penny."},
  {"id":"wingstop","name":"Wingstop","address":"1200 E 7th St","cuisine":"Wings","price":10,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats, Wingstop App","tags":["wings","quick","cheap","spicy","comfort"],"popularDishes":["Lemon Pepper Wings","Cajun Wings","Fries"],"vegetarianFriendly":false,"lunchHours":"10:30 AM - 12:00 AM","rating":3.9,"googleMapsUrl":"https://maps.google.com/?q=Wingstop+E+7th+Austin+TX","description":"Fast wings with every flavor you can imagine."},
  {"id":"thundercloud-subs","name":"Thundercloud Subs","address":"1608 Lavaca St","cuisine":"Sandwiches","price":8,"deliveryMinutes":10,"deliveryApps":"DoorDash, Favor","tags":["sandwiches","quick","cheap","classic","healthy"],"popularDishes":["California Club","NY Italian","Office Favorite"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 8:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Thundercloud+Subs+Lavaca+Austin+TX","description":"Austin's own sub chain since 1975. Keep it local."},
  {"id":"which-wich","name":"Which Wich","address":"1900 E MLK Jr Blvd","cuisine":"Sandwiches","price":10,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["sandwiches","quick","customizable","cheap"],"popularDishes":["Wicked","Thank You Turkey","Gyro"],"vegetarianFriendly":true,"lunchHours":"10:30 AM - 9:00 PM","rating":4,"googleMapsUrl":"https://maps.google.com/?q=Which+Wich+MLK+Austin+TX","description":"Build your own sandwich. Bag system is a vibe."},
  {"id":"ms-ps","name":"Ms. P's Electric Cock","address":"1900 E 12th St","cuisine":"Thai","price":13,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["thai","spicy","creative","sit-down","bold-flavors"],"popularDishes":["Pad Thai","Green Curry","Thai Iced Tea"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Ms+Ps+Electric+Cock+Austin+TX","description":"Funky Thai spot with legit curries and noodles."},
  {"id":"the-league","name":"The League Kitchen","address":"75 Rainey St","cuisine":"American","price":15,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["burgers","bar-food","outdoor","shareable","fun"],"popularDishes":["League Burger","Chicken Tenders","Loaded Nachos"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 12:00 AM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=The+League+Kitchen+Rainey+Austin+TX","description":"Sports bar on Rainey with solid burgers and tons of TVs."},
  {"id":"hillside-farmacy","name":"Hillside Farmacy","address":"1209 E 11th St","cuisine":"American","price":19,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["farm-to-table","brunch","outdoor","sit-down"],"popularDishes":["Farmacy Burger","Brisket Grilled Cheese","Seasonal Salad"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Hillside+Farmacy+Austin+TX","description":"Farm-to-table in a converted 1950s pharmacy."},
  {"id":"henbit","name":"Henbit","address":"2112 E 7th St","cuisine":"American","price":19,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["brunch","healthy","creative","outdoor"],"popularDishes":["Fried Chicken Biscuit","Grain Bowl","Pastries"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 3:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Henbit+Austin+TX","description":"Beautiful cafe with inventive brunch plates."},
  {"id":"la-barbecue","name":"La Barbecue","address":"2401 E Cesar Chavez St","cuisine":"BBQ","price":18,"deliveryMinutes":9,"deliveryApps":"DoorDash, Favor","tags":["smoky","outdoor","meat-lovers","hearty"],"popularDishes":["Brisket","Pulled Pork Sandwich","Beef Ribs"],"vegetarianFriendly":false,"lunchHours":"11:00 AM - 6:00 PM","rating":4.7,"googleMapsUrl":"https://maps.google.com/?q=La+Barbecue+Austin+TX","description":"Legendary East Austin BBQ with lines worth the wait."},
  {"id":"nixta-taqueria","name":"Nixta Taqueria","address":"2512 E 12th St","cuisine":"Mexican","price":14,"deliveryMinutes":10,"deliveryApps":"DoorDash, Favor","tags":["heirloom-corn","creative","unique","quick"],"popularDishes":["Duck Carnitas Taco","Migas Taco","Masa Fries"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 2:00 PM","rating":4.8,"googleMapsUrl":"https://maps.google.com/?q=Nixta+Taqueria+Austin+TX","description":"Heirloom corn tacos that redefine the taco game."},
  {"id":"oko","name":"OKO","address":"1308 E 6th St","cuisine":"Filipino","price":14,"deliveryMinutes":4,"deliveryApps":"DoorDash, UberEats","tags":["street-food","unique","bold-flavors","quick"],"popularDishes":["Sisig","Lumpia","Adobo Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=OKO+Filipino+Austin+TX","description":"Filipino street food with big bold flavors."},
  {"id":"old-thousand","name":"Old Thousand","address":"1000 E 11th St","cuisine":"Chinese","price":14,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["chinese","creative","noodles","sit-down"],"popularDishes":["General Tso's Chicken","Dan Dan Noodles","Salt & Pepper Ribs"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Old+Thousand+Austin+TX","description":"Modern Chinese that's anything but takeout basic."},
  {"id":"koriente","name":"Koriente","address":"621 E 7th St","cuisine":"Korean","price":12,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["korean","healthy","quick","cheap","bowls"],"popularDishes":["Bibimbap","Korean Tacos","Bulgogi Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Koriente+Austin+TX","description":"Healthy Korean bowls and tacos, fast and fresh."},
  {"id":"salty-sow","name":"Salty Sow","address":"1917 Manor Rd","cuisine":"American","price":20,"deliveryMinutes":9,"deliveryApps":"DoorDash, UberEats","tags":["gastropub","brunch","quality","sit-down","hearty"],"popularDishes":["Deviled Eggs","Pork Chop","Burger"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Salty+Sow+Austin+TX","description":"Gastropub with killer brunch and craft cocktails."},
  {"id":"jacobys","name":"Jacoby's Restaurant","address":"3235 E Cesar Chavez St","cuisine":"American","price":18,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["ranch","brunch","hearty","outdoor","comfort"],"popularDishes":["Brisket Eggs Benedict","Ranch Burger","Smoked Queso"],"vegetarianFriendly":true,"lunchHours":"8:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Jacobys+Restaurant+Austin+TX","description":"Ranch-to-table on the banks of the Colorado River."},
  {"id":"lazarus-brewing","name":"Lazarus Brewing","address":"1902 E 6th St","cuisine":"American","price":14,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats","tags":["brewery","bar-food","outdoor","chill","shareable"],"popularDishes":["Pizza","Tacos","Craft Beer"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 11:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Lazarus+Brewing+Austin+TX","description":"Chill brewery with solid food and great patio."},
  {"id":"1618-asian-fusion","name":"1618 Asian Fusion","address":"1618 E 6th St","cuisine":"Asian","price":15,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["asian","fusion","sushi","creative","sit-down"],"popularDishes":["Pad Thai","Sushi Rolls","Fried Rice"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=1618+Asian+Fusion+Austin+TX","description":"Pan-Asian with sushi, Thai, and Chinese under one roof."},
  {"id":"casa-colombia","name":"Casa Colombia","address":"1917 E Cesar Chavez St","cuisine":"Colombian","price":13,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats","tags":["colombian","authentic","hearty","comfort","cheap"],"popularDishes":["Bandeja Paisa","Empanadas","Arepa"],"vegetarianFriendly":true,"lunchHours":"10:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Casa+Colombia+Austin+TX","description":"Authentic Colombian homecooking with massive portions."},
  {"id":"tuk-tuk-thai","name":"Tuk Tuk Thai","address":"1209 E 7th St","cuisine":"Thai","price":13,"deliveryMinutes":6,"deliveryApps":"DoorDash, UberEats, Favor","tags":["thai","quick","authentic","cheap","spicy"],"popularDishes":["Pad See Ew","Massaman Curry","Tom Yum Soup"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:30 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Tuk+Tuk+Thai+Austin+TX","description":"Quick, affordable Thai with solid curry game."},
  {"id":"desano-pizza","name":"DeSano Pizza","address":"815 W 47th St","cuisine":"Pizza","price":15,"deliveryMinutes":10,"deliveryApps":"DoorDash, UberEats","tags":["pizza","neapolitan","quality","sit-down"],"popularDishes":["Margherita","Diavola","Calzone"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 10:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=DeSano+Pizza+Austin+TX","description":"Certified Neapolitan pizza with imported Italian ingredients."},
  {"id":"batch-kolaches","name":"Batch Craft Soda + Kolaches","address":"3220 Manor Rd","cuisine":"Bakery","price":9,"deliveryMinutes":10,"deliveryApps":"DoorDash, Favor","tags":["bakery","breakfast","cheap","quick","comfort"],"popularDishes":["Sausage Kolache","Fruit Kolache","Craft Soda"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Batch+Kolaches+Austin+TX","description":"Czech-Texas kolaches with creative fillings."},
  {"id":"pho-please","name":"Pho Please","address":"2600 E Cesar Chavez St","cuisine":"Vietnamese","price":12,"deliveryMinutes":9,"deliveryApps":"DoorDash, UberEats","tags":["pho","noodles","cheap","warm","authentic"],"popularDishes":["Pho Tai","Banh Mi","Vermicelli Bowl"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Pho+Please+Austin+TX","description":"Solid pho and banh mi right in East Austin."},
  {"id":"cenote","name":"Cenote","address":"1010 E Cesar Chavez St","cuisine":"Cafe","price":10,"deliveryMinutes":5,"deliveryApps":"DoorDash, Favor","tags":["coffee","light-lunch","outdoor","chill","quick"],"popularDishes":["Avocado Toast","Breakfast Tacos","Smoothie Bowl"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 6:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Cenote+Cesar+Chavez+Austin+TX","description":"Chill coffee shop with great light bites."},
  {"id":"better-half","name":"Better Half Coffee","address":"406 Walsh St","cuisine":"Cafe","price":12,"deliveryMinutes":7,"deliveryApps":"DoorDash, UberEats","tags":["coffee","brunch","outdoor","chill","healthy"],"popularDishes":["Breakfast Sandwich","Cold Brew","Grain Bowl"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 4:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Better+Half+Coffee+Austin+TX","description":"Spacious coffee bar with excellent food and patio."},
  {"id":"zilker-brewing","name":"Zilker Brewing","address":"1701 E 6th St","cuisine":"American","price":13,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["brewery","bar-food","outdoor","shareable","chill"],"popularDishes":["Brewery Burger","Pretzel","Craft Beer"],"vegetarianFriendly":true,"lunchHours":"12:00 PM - 10:00 PM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Zilker+Brewing+Austin+TX","description":"Great beer and solid pub food on E 6th."},
  {"id":"cuantos-tacos","name":"Cuantos Tacos","address":"1108 E 12th St","cuisine":"Mexican","price":8,"deliveryMinutes":7,"deliveryApps":"DoorDash, Favor","tags":["tacos","street-food","cheap","quick","authentic"],"popularDishes":["Birria Taco","Campechano","Loaded Fries"],"vegetarianFriendly":false,"lunchHours":"10:00 AM - 9:00 PM","rating":4.5,"googleMapsUrl":"https://maps.google.com/?q=Cuantos+Tacos+Austin+TX","description":"Birria tacos and loaded fries that go hard."},
  {"id":"veracruz-all-natural","name":"Veracruz All Natural","address":"1704 E Cesar Chavez St","cuisine":"Mexican","price":10,"deliveryMinutes":6,"deliveryApps":"DoorDash, Favor","tags":["tacos","fresh","authentic","cheap","quick"],"popularDishes":["Migas Taco","Green Salsa Chicken","Agua Frescas"],"vegetarianFriendly":true,"lunchHours":"7:00 AM - 3:00 PM","rating":4.6,"googleMapsUrl":"https://maps.google.com/?q=Veracruz+All+Natural+Cesar+Chavez+Austin+TX","description":"Famous migas tacos and fresh salsas from a beloved truck."},
  {"id":"buzz-mill","name":"Buzz Mill Coffee","address":"1505 Town Creek Dr","cuisine":"Cafe","price":10,"deliveryMinutes":6,"deliveryApps":"DoorDash, Favor","tags":["coffee","light-lunch","chill","outdoor","cheap"],"popularDishes":["Cold Brew","Breakfast Tacos","Pastries"],"vegetarianFriendly":true,"lunchHours":"6:00 AM - 12:00 AM","rating":4.2,"googleMapsUrl":"https://maps.google.com/?q=Buzz+Mill+Coffee+Austin+TX","description":"24-hour-ish coffee shop with great outdoor vibes."},
  {"id":"chipotle","name":"Chipotle","address":"1100 S Lamar Blvd","cuisine":"Mexican","price":11,"deliveryMinutes":8,"deliveryApps":"DoorDash, UberEats, Chipotle App","tags":["burritos","quick","cheap","customizable","healthy"],"popularDishes":["Burrito Bowl","Chicken Burrito","Chips & Guac"],"vegetarianFriendly":true,"lunchHours":"10:45 AM - 10:00 PM","rating":4.1,"googleMapsUrl":"https://maps.google.com/?q=Chipotle+S+Lamar+Austin+TX","description":"Build your own burrito bowl. Fast, reliable, everywhere."},
  {"id":"saigon-on-7th","name":"Saigon On 7th","address":"1302 E 7th St","cuisine":"Vietnamese","price":12,"deliveryMinutes":5,"deliveryApps":"DoorDash, UberEats","tags":["pho","banh-mi","cheap","authentic","warm"],"popularDishes":["Pho","Banh Mi","Spring Rolls"],"vegetarianFriendly":true,"lunchHours":"11:00 AM - 9:00 PM","rating":4.4,"googleMapsUrl":"https://maps.google.com/?q=Saigon+on+7th+Austin+TX","description":"Legit Vietnamese right on E 7th. Great pho and banh mi."},
  {"id":"food-heads","name":"Food Heads","address":"610 E Riverside Dr","cuisine":"Sandwiches","price":10,"deliveryMinutes":9,"deliveryApps":"DoorDash, Favor","tags":["sandwiches","cheap","quick","comfort","classic"],"popularDishes":["Philly Cheesesteak","Italian Sub","Turkey Club"],"vegetarianFriendly":true,"lunchHours":"10:00 AM - 9:00 PM","rating":4.3,"googleMapsUrl":"https://maps.google.com/?q=Food+Heads+Austin+TX","description":"No-nonsense sandwiches. Big portions, low price."}
];

export const cuisines = [...new Set(restaurants.map(r => r.cuisine))];

export const cuisineColors = {
  'BBQ': '#f97316', 'Mexican': '#22c55e', 'Pizza': '#ef4444',
  'Japanese': '#ec4899', 'Caribbean': '#14b8a6',
  'Italian': '#a855f7', 'Tex-Mex': '#eab308', 'American': '#3b82f6',
  'Argentine': '#06b6d4', 'Filipino': '#f59e0b', 'Chinese': '#e11d48',
  'Cafe': '#84cc16', 'Asian-BBQ': '#d946ef', 'Thai': '#10b981',
  'Burgers': '#f97316', 'Korean-Mexican': '#ec4899', 'Mediterranean': '#14b8a6',
  'Korean': '#e11d48', 'Hawaiian': '#3b82f6', 'Indian': '#f59e0b',
  'Salvadoran': '#a855f7', 'Wings': '#ef4444', 'Sandwiches': '#84cc16',
  'Colombian': '#f97316', 'Asian': '#ec4899', 'French': '#a855f7',
  'Vietnamese': '#06b6d4', 'Bakery': '#eab308',
};

export function getCuisineColor(cuisine) {
  return cuisineColors[cuisine] || '#ff6b35';
}

export function getRandom(arr = restaurants) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
